### ISSUE TITLE
Contact form isn't working

### ISSUE THREAD

**Issue by JackHull** [devlom/grav-skeleton-hola#1]
Hi, when trying to send the contact form the console returns a 404 error, as the form tries to post to /home/_contact, but that route seems to be non-existent. Any fix for this or possible source of error?

Thanks in advance!

**Comment by hexplor** [comment]
Hey,
You're trying using smtp or sendmail ? Will take a look today at this .

**Comment by hexplor** [comment]
Ok, yeah :) Fixed :)
